### PR TITLE
Fix TypeScript error when writing higher order components while using Emotion's JSX namespace

### LINKED ISSUE #3245: v11.13.3 type error with Next
**Current behavior:**

type Error Occurs after v11.13.3

```
const withAuth = <P extends object>(WrappedComponent: NextPage<P>) => {
  const AuthComponent = (props: P) => {
    ...my logic
    return <WrappedComponent {...props} />;
  }
}
```

**Expected behavior:**

Type Error is fixed , if it's not error. is there any method to solve this type error?

**Environment information:**

- `react` version: 18.3.1
- `@emotion/react` version: 11.13.3

### LINKED ISSUE #3261: Props not assignable to `LibraryManagedAttributes` type error
**Current behavior:**

After updating `@emotion/react` to `11.13.3`, I start seeing the following type error in HOC (higher-order components):

```
src/hoc.tsx:7:13 - error TS2322: Type 'P' is not assignable to type 'IntrinsicAttributes & LibraryManagedAttributes<FC<P>, P>'.
  Type 'Record<string, unknown>' is not assignable to type 'IntrinsicAttributes & LibraryManagedAttributes<FC<P>, P>'.
    Type 'Record<string, unknown>' is not assignable to type 'LibraryManagedAttributes<FC<P>, P>'.
      Type 'P' is not assignable to type 'LibraryManagedAttributes<FC<P>, P>'.
        Type 'Record<string, unknown>' is not assignable to type 'LibraryManagedAttributes<FC<P>, P>'.

7     return <C {...props} />;
              ~


Found 1 error in src/hoc.tsx:7
```

Here is the code that produces this type error above:

```tsx
const Component: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return <div>{children}</div>;
};

export const hoc = <P extends Record<string, unknown>>(C: React.FC<P>) => {
  return (props: P) => {
    return <C {...props} />;
  };
};

hoc(Component);
```

After downgrading `@emotion/react` to `11.13.0`, the error stops appearing anymore.

**To reproduce:**

1. Clone this repository for reproduction: https://github.com/shawnrivers/emotion-react-hoc-type-error
2. Run `npm i`
3. Run `npm run type-check`

**Expected behavior:**

No type error inside the HOC (which is the behavior before `@emotion.react@11.13.3`.

**Environment information:**

- `react` version: 18.3.1
- `@emotion/react` version: 11.13.3

### PR DESCRIPTION
**Pull request by emmatown**
This regressed in #3232

Fixes #3245
Fixes #3261

### CODE REVIEW

**Comment by emmatown** [comment]
Hmmm, actually this is wrong and I think the right solution is probably not being distributive and knowingly not supporting the use case of #3185

**Comment by Andarist** [comment]
> Being able to write a higher order component at all without type errors is more valuable than a component conditionally supporting className having the css prop accessible in types.

I agree. It seems that TS isn't able to relate a non-conditional type to a distributive conditional type (this is the only branch that checks `targetFlags & TypeFlags.Conditional` outside of `sourceFlags & TypeFlags.Conditional`):
https://github.dev/microsoft/TypeScript/blob/6a00bd2422ffa46c13ac8ff81d7b4b1157e60ba7/src/compiler/checker.ts#L23200-L23221

It doesn't even work in cases like this ([TS playground](https://www.typescriptlang.org/play/?ts=5.8.0-dev.20241212#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwxAGcMAeAFQD4AKAKHngAcBGALnnIBp6mAmd8vBAAPQqmBF4aANaocAd3wB+DvABk8AN7wwRIkvYy5i+AF947VCABuIGNwCU7azizAA3LVpg8JePJgoRkY7eABeeFIABQB9GKFREHFJHAAjACtwDBpGGBxGInZYmIdwyi0eQhJqXPyiTiY8godPU08gA)):
```ts
declare function test<T>(
  p1: T,
  p2: T extends unknown ? T & { css?: unknown } : never,
): void;

const wrapper = <P__ extends object>(props: P__) => {
  test(
    props,
    props // error
  );
};
```

It seems that perhaps this rule is overly restrictive but I don't know how to safely loosen it to handle this case. And any potential fix wouldn't land in TS soon enough for us anyway - so ye, we have to revert that PR.

**Comment by Andarist** [comment]
I opened a PR that could fix this but I can't really say with confidence that it's a correct one: https://github.com/microsoft/TypeScript/pull/60817
