### ISSUE TITLE
@emotion/react v11.4.0 does not work with nextjs@10.2.0 and webpack 5

### ISSUE THREAD

**Issue by skratchdot** [emotion-js/emotion#2378]
**Current behavior:**

I have a nextjs app using 10.2 (they upgraded to webpack v5).

I can run `npm run dev` with `@emotion/react@11.1.5` and everything works fine.

If I upgrade to `@emotion/react@11.4.0`:

<img width="313" alt="image" src="https://user-images.githubusercontent.com/434470/118364812-092b7000-b568-11eb-8285-02430e9a2b71.png">

I see the following error:

`Module not found: Can't resolve './emotion-element-4fbd89c5.browser.esm.js'`

<img width="640" alt="image" src="https://user-images.githubusercontent.com/434470/118364892-5dceeb00-b568-11eb-92ac-66cdff7e9f69.png">

The way to fix is by forcing nextjs to use webpack 4.

So,

`@emotion/react@11.1.5`
- works with nextjs@10.2 configured for webpack 4
- works with nextjs@10.2 configured for webpack 5

`@emotion/react@11.4.0`
- works with nextjs@10.2 configured for webpack 4
- does not work with nextjs@10.2 configured for webpack 5

Also- it appears I'm not using emotion directly- I'm using it due to:
```
    "@material-ui/core": "^5.0.0-alpha.25",
    "@material-ui/icons": "^5.0.0-alpha.24",
    "@material-ui/lab": "^5.0.0-alpha.25",
```

So this could very well be a material-ui issue

**To reproduce:**

I will try to setup a repo with a reproducible case. I can't share my repo at the moment since it's private, but I should be able to narrow down the issue and update this ticket.

This might just be a configuration issue, but things definitely "break" when `@emotion/react` is the only item I upgrade.  I'm just logging here in case anyone has ran into the same issue.

**Expected behavior:**

I expect to be able to use 10.4.0 in my nextjs 10.2 / webpack v5 repo.

**Environment information:**

- `react` version: 17.0.2
- `@emotion/react` version: 11.4.0

**Comment by skratchdot** [comment]
I'm going to close this until I can make a reproducible case. A very simple nextjs / material-ui site is working for me.

**Comment by VictorGlindasPaf** [comment]
I'm having a similar issue.
Also using nextjs and updating `@emotion/react` from `11.1.5` to `11.4.0`.
Reverting to webpack 4 does not help for me.

```sh
TypeError: stylis.middleware is not a function
    at Object.createCache [as default] (/Users/user/Documents/Repositories/project/node_modules/@emotion/styled/node_modules/@emotion/cache/dist/emotion-cache.cjs.dev.js:308:30)
    at Wrapper (/Users/user/Documents/Repositories/project/node_modules/@emotion/styled/node_modules/@emotion/react/dist/emotion-element-deca0de5.cjs.dev.js:51:48)
    at processChild (/Users/user/Documents/Repositories/project/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/Users/user/Documents/Repositories/project/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/Users/user/Documents/Repositories/project/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/Users/user/Documents/Repositories/project/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToString (/Users/user/Documents/Repositories/project/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at Object.renderPage (/Users/user/Documents/Repositories/project/node_modules/next/dist/next-server/server/render.js:54:854)
    at Function.getInitialProps (webpack-internal:///../../node_modules/next/dist/pages/_document.js:211:19)
    at loadGetInitialProps (/Users/user/Documents/Repositories/project/node_modules/next/dist/next-server/lib/utils.js:5:101)
    at renderToHTML (/Users/user/Documents/Repositories/project/node_modules/next/dist/next-server/server/render.js:54:1145)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/user/Documents/Repositories/project/node_modules/next/dist/next-server/server/next-server.js:112:97
    at async /Users/user/Documents/Repositories/project/node_modules/next/dist/next-server/server/next-server.js:105:142
    at async DevServer.renderToHTMLWithComponents (/Users/user/Documents/Repositories/project/node_modules/next/dist/next-server/server/next-server.js:137:387)
    at async DevServer.renderToHTML (/Users/user/Documents/Repositories/project/node_modules/next/dist/next-server/server/next-server.js:138:610)
    ```
