### ISSUE TITLE
Cannot find module 'babel-plugin-emotion' after updating to 7.3.0

### ISSUE THREAD

**Issue by ChrisW-B** [emotion-js/emotion#305]
- `emotion` version: 7.3.0
- `react` version: 16.0.0-rc.2

Relevant code.

###webpack.config.js
```javascript

{
      test: /\.jsx?$|\.js?$/,
      exclude: /node_modules/,
      use: [{
        loader: 'babel-loader',
        options: {
          presets: [
            ['es2015', { modules: false }], 'react', 'stage-0'
          ],
          plugins: [
            ['emotion/babel'],
            ['transform-react-remove-prop-types', { mode: 'remove', removeImport: true }]
          ]
        }
      }]
    }

```
###Other files
```javascript
 import { injectGlobal } from 'emotion/react';
```
or
```javascript
 import styled from 'emotion/react';
```
What you did:
After updating from emotion 7.2.2 to 7.3.0 (react-emotion, emotion, and babel-plugin-emotion), webpack fails to build. Reverting to 7.2.2 corrects this issue

I feel like this more likely a problem with something I did, but I cannot figure out what it might be

What happened:

Error is
```
ERROR in ./react/index.js
Module build failed: Error: Cannot find module 'babel-plugin-emotion'
...
```

**Comment by wKovacs64** [comment]
@ChrisW-B Try 7.3.1, which was released moments after 7.3.0.

**Comment by ChrisW-B** [comment]
Perfect! Guess I just snuck in there between updates, thanks for getting back so quickly!
