### ISSUE TITLE
Issue with typescript & css prop on version 11.0.0-rc.0

### ISSUE THREAD

**Issue by karibertils** [emotion-js/emotion#2045]
**Current behavior:**

When using the css prop on version 11.0.0-rc.0 I get.
```
Property 'css' does not exist on type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'
```

The css prop works fine on version 11.0.0-next.13 and below

**To reproduce:**
Use the following type definiton and make sure you are on 11.0.0-rc.0 or earlier version of @emotion/react
```
import '@emotion/react'

type MyTheme = {
	color: 'black'
}

declare module '@emotion/react' {
	export interface Theme extends MyTheme {}
}
```

**Expected behavior:**

Expected it to continue working after updating.

**Environment information:**

```
                "typescript": "^4.0.3",
                "react": "^17.0.0-rc.3",
                "react-dom": "17.0.0-rc.3",
                "@types/react": "16.9.49",
                "@types/react-dom": "16.9.8",
                "@emotion/cache": "11.0.0-rc.0",
                "@emotion/react": "11.0.0-rc.0",
                "@emotion/styled": "11.0.0-rc.0",
```

I don't know if any other packages are relevant.

**Comment by Andarist** [comment]
Do you use `@jsx` pragma?

**Comment by karibertils** [comment]
Hm no. I am using fuse-box with
```
			plugins: [
				pluginCSSInJSX({
					autoInject: true,
					autoLabel: true,
					cssPropOptimization: true,
					emotionCoreAlias: '@emotion/react',
					jsxFactory: 'jsx',
					labelFormat: '[dirname]--[local]',
					sourceMap: true,
					test: /src\/(.*?)\.(js|jsx|ts|tsx)$/,
				}),
			],
```

tsconfig.json
```
{
	"compilerOptions": {
		"allowSyntheticDefaultImports": true,
		"baseUrl": ".",
		"declaration": false,
		"downlevelIteration": true,
		"jsx": "react",
		"lib": ["ESNext", "es2018", "dom"],
		"moduleResolution": "Node",
		"outDir": "./dist/out-tsc",
		"sourceMap": true,
		"module": "ESNext",
		"target": "ESNext",
		"types": ["@emotion/react"],
		"resolveJsonModule": true
	}
}
```

I tested adding the @jsx pragma to the top and the css prop works fine on 11.0.0-rc.0 with that.

But with 11.0.0-next.13 it works fine without @jsx pragma at top. What could cause that ?

**Comment by Andarist** [comment]
In such a case you need to opt into css prop types now. Take a look at this changeset - it explains most of it:
https://github.com/emotion-js/emotion/pull/1941/files#diff-ab05664ae7c0613a636689f5b615463b4e178f1853b2112dbd721944bc13b5a6R7

**Comment by karibertils** [comment]
Yep that works

Thank you @Andarist
