### ISSUE TITLE
v11.5.0 breaks the Theme export 

### ISSUE THREAD

**Issue by Snaptags** [emotion-js/emotion#2519]
**Current behavior:**

Version 11.5.0 breaks the Theme export in our library. When using the library in React applications I now get
```
 error TS2339: Property 'color' does not exist on type 'Theme'.
```
This used to work using v11.4.1 (and still does, if I just downgrade)

**To reproduce:**

n/a - I don't think I can show this in a CodeSandbox example :(

**Expected behavior:**

TypeScript complies the React app without error

**Environment information:**

- `react` version: 17.0.2
- `@emotion/react` version: 11.5.0
- `typescript` version: 4.4.4

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by Snaptags** [comment]
I'll try to add a repro case, will take some time though…
